---
name: tzinfo
version: '2.0'
source:
  type: git
  name: ruby/gem_rbs_collection
  revision: '09beb2100db10cbf4773ed0e71ddf79280a2f275'
  remote: https://github.com/ruby/gem_rbs_collection.git
  repo_dir: gems
