---
name: tzinfo
version: '2.0'
source:
  type: git
  name: ruby/gem_rbs_collection
  revision: 71fb7ae83789ae150bdee1cd8a7cd3035b5d79e2
  remote: https://github.com/ruby/gem_rbs_collection.git
  repo_dir: gems
